# Generated by Django 3.1.1 on 2020-09-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rakes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
