# Generated by Django 3.1.1 on 2020-09-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rakes', '0003_post_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='address',
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
