# Generated by Django 3.1.1 on 2020-09-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rakes', '0004_auto_20200904_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofProduct', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='')),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
    ]
